# Generated by Django 5.2 on 2025-05-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
