[pytest]
minversion = 6.0
pythonpath = src
DJANGO_SETTINGS_MODULE = src.django_project.settings
python_files = tests.py test_*.py *_tests.py *_test.py
addopts = -ra -q --reuse-db

markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    serial
    integration: mark the test as an integration test
    skip_fake_auth: marks tests that should be skipped when using fake auth