# Generated by Django 5.2 on 2025-05-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiovideomedia",
            name="checksum",
        ),
        migrations.RemoveField(
            model_name="imagemedia",
            name="checksum",
        ),
    ]
