# Generated by Django 5.2 on 2025-05-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0002_remove_audiovideomedia_checksum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiovideomedia",
            name="media_type",
            field=models.CharField(
                choices=[("VIDEO", "VIDEO"), ("TRAILER", "TRAILER")],
                default="VIDEO",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
